public with sharing class ConstantForMMG {
    
    public static final string strHostURL = 'https://api.globalgiving.org';
    public static final string strURLForRequiredData = '/api/public/projectservice/all/projects/active';
    public static final string strAPI_Key = 'dd9bcdbd-8d89-43c6-8a62-ec9b1768ca6f';
    public static final string strContentType = 'Content-Type';
    public static final string strContentForm = 'xml/json';
}