/************************************************************************
 Class Name: democonstructor
 Created Date:11/7/2015
 Description: simple demo constructor
*************************************************************************/  
public class democonstructor {  
    public democonstructor(integer i, string n)
    {
       integer stud_id=i;
        string name=n;
        system.debug('ID is:' + stud_id);
        system.debug('Name is'+ name);
    }
        
   }