/************************************************************************
 Class Name: subclass
 Created Date:11/7/2015
 Description: subclass overriding abstract method
*************************************************************************/ 
public class subclass extends classForinheritance{
    
    public override void  displayingWord() {
         system.debug('This is sub class');
    } 
   }